### ISSUE TITLE
[SUGGESTION] Instead of manual and slow, why not a quick and more quantity catch.

### ISSUE THREAD

**Issue by makumaku1974** [GravityCY/FishingButGood#1]
This idea is based on Terraria where a one specific fishing rod can multiply bobbers in one swing, hence the idea is that if you created this version of enchantment. It is not obtainable via enchanting table rather by exploration.

**Comment by GravityCY** [comment]
Hey, I'm not entirely sure what your suggestion is.

Currently there's an enchantment you either get from fishing or killing the Elder Guardian, you use it to enchant your fishing rod to allow you to throw multiple fishing hooks, so are you suggesting to make it a new fishing rod type, rather than an enchantment? Because everything you're saying is kind of the way it's implemented

**Comment by makumaku1974** [comment]
Oh so i have to kill the Elder Guardian I see. Thanks for the tip. Nvm what I said and also was not thinking about a new rod. But yeah ill try out the method.

**Comment by GravityCY** [comment]
The only thing I might change eventually is the chance of getting it from the Elder Guardian cause right now it's a 25% chance to get it, and I feel maybe that should be a higher chance of getting it... not sure.

**Comment by makumaku1974** [comment]
keep it as 25%... It's a bit op.
